Report= "Xpath=//a[@class='reportsNavItem ng-star-inserted']"
Survey= "Xpath=//span[text()='Engagement']"
Team_summary= "Xpath=//div[@class='header mleReport']"
SurveyParticipation= "Xpath=//p[text()='Survey Participation']"
Keyoutcome= "Xpath=//h2[text()=' Key Outcome ']"
AllScores= "Xpath=//p[text()='All Scores']"
PrimaryHierarchy= "Xpath=(//span[text()='Manager'])[2]"
ViewComments="Xpath=//button[text()=' View Comments ']"
AllCommentcount= "Xpath=(//h3[@class='itemValue'])[2]"
CommentSlider= "Xpath=/html/body/glint-root/div/div/div/main/div/glint-engagement-report/glint-report-detail/glint-comment-slidey/glint-slidey/div/div[3]/div/header/div"
KeyoutcomeScoreTrend= "Xpath=//div[@class='item ng-star-inserted']"
Teamsummarytext="Xpath=//h1[text()=' Team Summary ']"
